import { PERMISSIONS } from "../constants/permissions";
import { ROLES } from "../constants/roles";

export const ROLE_PERMISSIONS = {

    [ROLES.SUPER_ADMIN]: [

        PERMISSIONS.DASHBOARD,

        PERMISSIONS.INVENTORY,

        PERMISSIONS.MATERIALS_INWARD,

        PERMISSIONS.MATERIALS_OUTWARD,

        PERMISSIONS.CREATE_RMR,

        PERMISSIONS.CREATE_MANIFEST,

        PERMISSIONS.REPORTS,

        PERMISSIONS.USERS,

        PERMISSIONS.SETTINGS,

        PERMISSIONS.AUDIT,

    ],

    [ROLES.WAREHOUSE_MANAGER]: [

        PERMISSIONS.DASHBOARD,

        PERMISSIONS.INVENTORY,

        PERMISSIONS.MATERIALS_INWARD,

        PERMISSIONS.MATERIALS_OUTWARD,

        PERMISSIONS.CREATE_RMR,

        PERMISSIONS.CREATE_MANIFEST,

        PERMISSIONS.REPORTS,

    ],

    [ROLES.REQUESTOR]: [

        PERMISSIONS.DASHBOARD,

        PERMISSIONS.CREATE_RMR,

    ],

    [ROLES.VIEWER]: [

        PERMISSIONS.DASHBOARD,

        PERMISSIONS.REPORTS,

    ],

};